name: Mongoose AutoIncrement

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    branches:
      - 'master'
    inputs:
      release:
        description: Release
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubutntu-20.04
    if: ${{ !contains(github.event.head_commit.message, '[build skip]') }}
    steps:
      - name: Install gnupg and curl
        run: sudo apt-get install gnupg curl

      - name: Import the public key
        run: curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor

      - name: Create a list of file for MongoDB
        run: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

      - name: Reload packages
        run: sudo apt-get update

      - name: Install MongoDB packages
        run: sudo apt-get install -y mongodb-org

      - name: Start MongoDB
        run: sudo systemctl start mongod
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - name: Setup NodeJS v20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          registry-url: 'https://registry.npmjs.org'
          scope: '@alec016'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  test:
    if: ${{ !contains(github.event.head_commit.message, '[test skip]') }}
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Run tests
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{secrets.MONGO_INITDB_ROOT_USERNAME}}
          MONGO_INITDB_ROOT_PASSWORD: ${{secrets.MONGO_INITDB_ROOT_PASSWORD}}
        run: npm run test

  publish:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.release == true }}
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish
