name: Mongoose AutoIncrement

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    branches:
      - 'master'
    inputs:
      release:
        description: Release
        required: true
        type: boolean
        default: false

jobs:
  mongo_container:
    runs-on: ubuntu-latest
    container:
      image: mongodb/mongodb-community-server
      env:
        MONGO_INITDB_DATABASE: 'knowledge'
        MONGODB_INITDB_ROOT_USERNAME: ${{secrets.MONGO_INITDB_ROOT_USERNAME}}
        MONGO_INITDB_ROOT_PASSWORD: ${{secrets.MONGO_INITDB_ROOT_PASSWORD}}

  test:
    runs-on: ubuntu-latest
    needs: mongo_container
    if: |
      !contains(github.event.head_commit.message, '[test skip]')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - name: Setup NodeJS v20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          registry-url: 'https://registry.npmjs.org'
          scope: '@alec016'

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{secrets.MONGO_INITDB_ROOT_USERNAME}}
          MONGO_INITDB_ROOT_PASSWORD: ${{secrets.MONGO_INITDB_ROOT_PASSWORD}}
        run: npm run test

  build:
    if: |
      !contains(github.event.head_commit.message, '[build skip]')
    needs: test
    runs-on: ubutntu-latest
    steps:
      - name: Build
        run: npm run build

  publish:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.release == true }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish
